//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 10:17:21 AM AMT 
//


package com.bank.DTO.ru.cbr.ed.v2;

import jakarta.xml.bind.annotation.*;

import java.math.BigInteger;


/**
 * SWIFT BICs of Participant.
 * 
 * <p>Java class for SWBICList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SWBICList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="SWBIC" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}BICSWIFTIDType" /&gt;
 *       &lt;attribute name="DefaultSWBIC" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}IndicatorType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SWBICList")
public class SWBICList {

    @XmlAttribute(name = "SWBIC", required = true)
    protected String swbic;
    @XmlAttribute(name = "DefaultSWBIC", required = true)
    protected Boolean defaultSWBIC;

    /**
     * Gets the value of the swbic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWBIC() {
        return swbic;
    }

    /**
     * Sets the value of the swbic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWBIC(String value) {
        this.swbic = value;
    }

    /**
     * Gets the value of the defaultSWBIC property.
     * 
     */
    public Boolean isDefaultSWBIC() {
        return defaultSWBIC;
    }

    /**
     * Sets the value of the defaultSWBIC property.
     * 
     */
    public void setDefaultSWBIC(Boolean value) {
        this.defaultSWBIC = value;
    }

}
